/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.dbofflinestorage.school_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvAvgfunctionResponse implements Serializable {


    @ColumnAlias("avg(MARKS_SECURED)")
    private Double avg_marksSecured_;

    public Double getAvg_marksSecured_() {
        return this.avg_marksSecured_;
    }

    public void setAvg_marksSecured_(Double avg_marksSecured_) {
        this.avg_marksSecured_ = avg_marksSecured_;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvAvgfunctionResponse)) return false;
        final SvAvgfunctionResponse svAvgfunctionResponse = (SvAvgfunctionResponse) o;
        return Objects.equals(getAvg_marksSecured_(), svAvgfunctionResponse.getAvg_marksSecured_());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAvg_marksSecured_());
    }
}