/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.dbofflinestorage.school_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvLengthFunctionResponse implements Serializable {


    @ColumnAlias("ADDRESS")
    private String address;

    @ColumnAlias("ADDRESS_LENGTH")
    private Long addressLength;

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Long getAddressLength() {
        return this.addressLength;
    }

    public void setAddressLength(Long addressLength) {
        this.addressLength = addressLength;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvLengthFunctionResponse)) return false;
        final SvLengthFunctionResponse svLengthFunctionResponse = (SvLengthFunctionResponse) o;
        return Objects.equals(getAddress(), svLengthFunctionResponse.getAddress()) &&
                Objects.equals(getAddressLength(), svLengthFunctionResponse.getAddressLength());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAddress(),
                getAddressLength());
    }
}