/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.dbofflinestorage.school_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvLowerFunctionResponse implements Serializable {


    @ColumnAlias("FIRSTNAME")
    private String firstname;

    @ColumnAlias("LASTNAME")
    private String lastname;

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvLowerFunctionResponse)) return false;
        final SvLowerFunctionResponse svLowerFunctionResponse = (SvLowerFunctionResponse) o;
        return Objects.equals(getFirstname(), svLowerFunctionResponse.getFirstname()) &&
                Objects.equals(getLastname(), svLowerFunctionResponse.getLastname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFirstname(),
                getLastname());
    }
}