/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.dbofflinestorage.school_db.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvSubStrResponse implements Serializable {


    @ColumnAlias("SHORTEN_CITY")
    private String shortenCity;

    public String getShortenCity() {
        return this.shortenCity;
    }

    public void setShortenCity(String shortenCity) {
        this.shortenCity = shortenCity;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvSubStrResponse)) return false;
        final SvSubStrResponse svSubStrResponse = (SvSubStrResponse) o;
        return Objects.equals(getShortenCity(), svSubStrResponse.getShortenCity());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getShortenCity());
    }
}