/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.dbofflinestorage.offlinedatabasedefined.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvHiddenFieldsResponse implements Serializable {


    @ColumnAlias("id")
    private Integer id;

    @ColumnAlias("first_name")
    private String firstName;

    @ColumnAlias("last_name")
    private String lastName;

    @ColumnAlias("fullname")
    private String fullname;

    @ColumnAlias("email")
    private String email;

    @ColumnAlias("Datetime Col")
    private LocalDateTime datetimeCol;

    @ColumnAlias("Timestamp Col")
    private Timestamp timestampCol;

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFullname() {
        return this.fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    public Timestamp getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(Timestamp timestampCol) {
        this.timestampCol = timestampCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvHiddenFieldsResponse)) return false;
        final SvHiddenFieldsResponse svHiddenFieldsResponse = (SvHiddenFieldsResponse) o;
        return Objects.equals(getId(), svHiddenFieldsResponse.getId()) &&
                Objects.equals(getFirstName(), svHiddenFieldsResponse.getFirstName()) &&
                Objects.equals(getLastName(), svHiddenFieldsResponse.getLastName()) &&
                Objects.equals(getFullname(), svHiddenFieldsResponse.getFullname()) &&
                Objects.equals(getEmail(), svHiddenFieldsResponse.getEmail()) &&
                Objects.equals(getDatetimeCol(), svHiddenFieldsResponse.getDatetimeCol()) &&
                Objects.equals(getTimestampCol(), svHiddenFieldsResponse.getTimestampCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getFirstName(),
                getLastName(),
                getFullname(),
                getEmail(),
                getDatetimeCol(),
                getTimestampCol());
    }
}