/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.dbofflinestorage.offlineclassicdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvAndOrResponse implements Serializable {


    @ColumnAlias("orderNumber")
    private Integer orderNumber;

    @ColumnAlias("orderDate")
    private Date orderDate;

    @ColumnAlias("requiredDate")
    private Date requiredDate;

    @ColumnAlias("shippedDate")
    private Date shippedDate;

    @ColumnAlias("status")
    private String status;

    @ColumnAlias("comments")
    private String comments;

    @ColumnAlias("customerNumber")
    private Integer customerNumber;

    @ColumnAlias("DatetimeCol")
    private LocalDateTime datetimeCol;

    @ColumnAlias("TimestampCol")
    private Timestamp timestampCol;

    public Integer getOrderNumber() {
        return this.orderNumber;
    }

    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    public Date getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    public Date getRequiredDate() {
        return this.requiredDate;
    }

    public void setRequiredDate(Date requiredDate) {
        this.requiredDate = requiredDate;
    }

    public Date getShippedDate() {
        return this.shippedDate;
    }

    public void setShippedDate(Date shippedDate) {
        this.shippedDate = shippedDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public Integer getCustomerNumber() {
        return this.customerNumber;
    }

    public void setCustomerNumber(Integer customerNumber) {
        this.customerNumber = customerNumber;
    }

    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    public Timestamp getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(Timestamp timestampCol) {
        this.timestampCol = timestampCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvAndOrResponse)) return false;
        final SvAndOrResponse svAndOrResponse = (SvAndOrResponse) o;
        return Objects.equals(getOrderNumber(), svAndOrResponse.getOrderNumber()) &&
                Objects.equals(getOrderDate(), svAndOrResponse.getOrderDate()) &&
                Objects.equals(getRequiredDate(), svAndOrResponse.getRequiredDate()) &&
                Objects.equals(getShippedDate(), svAndOrResponse.getShippedDate()) &&
                Objects.equals(getStatus(), svAndOrResponse.getStatus()) &&
                Objects.equals(getComments(), svAndOrResponse.getComments()) &&
                Objects.equals(getCustomerNumber(), svAndOrResponse.getCustomerNumber()) &&
                Objects.equals(getDatetimeCol(), svAndOrResponse.getDatetimeCol()) &&
                Objects.equals(getTimestampCol(), svAndOrResponse.getTimestampCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrderNumber(),
                getOrderDate(),
                getRequiredDate(),
                getShippedDate(),
                getStatus(),
                getComments(),
                getCustomerNumber(),
                getDatetimeCol(),
                getTimestampCol());
    }
}