/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.dbofflinestorage.offlineclassicdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvInoperatorResponse implements Serializable {


    @ColumnAlias("productCode")
    private String productCode;

    @ColumnAlias("productName")
    private String productName;

    @ColumnAlias("productLine")
    private String productLine;

    @ColumnAlias("productScale")
    private String productScale;

    @ColumnAlias("productVendor")
    private String productVendor;

    @ColumnAlias("productDescription")
    private String productDescription;

    @ColumnAlias("quantityInStock")
    private Short quantityInStock;

    @ColumnAlias("buyPrice")
    private BigDecimal buyPrice;

    @ColumnAlias("MSRP")
    private BigDecimal msrp;

    @ColumnAlias("DatetimeCol")
    private LocalDateTime datetimeCol;

    @ColumnAlias("TimestampCol")
    private Timestamp timestampCol;

    public String getProductCode() {
        return this.productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getProductLine() {
        return this.productLine;
    }

    public void setProductLine(String productLine) {
        this.productLine = productLine;
    }

    public String getProductScale() {
        return this.productScale;
    }

    public void setProductScale(String productScale) {
        this.productScale = productScale;
    }

    public String getProductVendor() {
        return this.productVendor;
    }

    public void setProductVendor(String productVendor) {
        this.productVendor = productVendor;
    }

    public String getProductDescription() {
        return this.productDescription;
    }

    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    public Short getQuantityInStock() {
        return this.quantityInStock;
    }

    public void setQuantityInStock(Short quantityInStock) {
        this.quantityInStock = quantityInStock;
    }

    public BigDecimal getBuyPrice() {
        return this.buyPrice;
    }

    public void setBuyPrice(BigDecimal buyPrice) {
        this.buyPrice = buyPrice;
    }

    public BigDecimal getMsrp() {
        return this.msrp;
    }

    public void setMsrp(BigDecimal msrp) {
        this.msrp = msrp;
    }

    public LocalDateTime getDatetimeCol() {
        return this.datetimeCol;
    }

    public void setDatetimeCol(LocalDateTime datetimeCol) {
        this.datetimeCol = datetimeCol;
    }

    public Timestamp getTimestampCol() {
        return this.timestampCol;
    }

    public void setTimestampCol(Timestamp timestampCol) {
        this.timestampCol = timestampCol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvInoperatorResponse)) return false;
        final SvInoperatorResponse svInoperatorResponse = (SvInoperatorResponse) o;
        return Objects.equals(getProductCode(), svInoperatorResponse.getProductCode()) &&
                Objects.equals(getProductName(), svInoperatorResponse.getProductName()) &&
                Objects.equals(getProductLine(), svInoperatorResponse.getProductLine()) &&
                Objects.equals(getProductScale(), svInoperatorResponse.getProductScale()) &&
                Objects.equals(getProductVendor(), svInoperatorResponse.getProductVendor()) &&
                Objects.equals(getProductDescription(), svInoperatorResponse.getProductDescription()) &&
                Objects.equals(getQuantityInStock(), svInoperatorResponse.getQuantityInStock()) &&
                Objects.equals(getBuyPrice(), svInoperatorResponse.getBuyPrice()) &&
                Objects.equals(getMsrp(), svInoperatorResponse.getMsrp()) &&
                Objects.equals(getDatetimeCol(), svInoperatorResponse.getDatetimeCol()) &&
                Objects.equals(getTimestampCol(), svInoperatorResponse.getTimestampCol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getProductCode(),
                getProductName(),
                getProductLine(),
                getProductScale(),
                getProductVendor(),
                getProductDescription(),
                getQuantityInStock(),
                getBuyPrice(),
                getMsrp(),
                getDatetimeCol(),
                getTimestampCol());
    }
}