/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.dbofflinestorage.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StandardDetails generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`STANDARD_DETAILS`", uniqueConstraints = {
            @UniqueConstraint(name = "`UK_STANDARD_DETAILS_STAN4v4IK`", columnNames = {"`STANDARD_CODE`"})})
public class StandardDetails implements Serializable {

    private Integer standardId;
    private String standardCode;
    private String standardName;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`STANDARD_ID`", nullable = false, scale = 0, precision = 10)
    public Integer getStandardId() {
        return this.standardId;
    }

    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }

    @Column(name = "`STANDARD_CODE`", nullable = false, length = 255)
    public String getStandardCode() {
        return this.standardCode;
    }

    public void setStandardCode(String standardCode) {
        this.standardCode = standardCode;
    }

    @Column(name = "`STANDARD_NAME`", nullable = false, length = 255)
    public String getStandardName() {
        return this.standardName;
    }

    public void setStandardName(String standardName) {
        this.standardName = standardName;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof StandardDetails)) return false;
        final StandardDetails standardDetails = (StandardDetails) o;
        return Objects.equals(getStandardId(), standardDetails.getStandardId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getStandardId());
    }
}