/*Copyright (c) 2015-2016 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/
package com.dbofflinestorage.school_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.dbofflinestorage.school_db.Academics;
import com.dbofflinestorage.school_db.StandardDetails;


/**
 * ServiceImpl object for domain model class StandardDetails.
 *
 * @see StandardDetails
 */
@Service("School_DB.StandardDetailsService")
@Validated
public class StandardDetailsServiceImpl implements StandardDetailsService {

    private static final Logger LOGGER = LoggerFactory.getLogger(StandardDetailsServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("School_DB.AcademicsService")
    private AcademicsService academicsService;

    @Autowired
    @Qualifier("School_DB.StandardDetailsDao")
    private WMGenericDao<StandardDetails, Integer> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<StandardDetails, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "School_DBTransactionManager")
    @Override
    public StandardDetails create(StandardDetails standardDetails) {
        LOGGER.debug("Creating a new StandardDetails with information: {}", standardDetails);

        StandardDetails standardDetailsCreated = this.wmGenericDao.create(standardDetails);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(standardDetailsCreated);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public StandardDetails getById(Integer standarddetailsId) {
        LOGGER.debug("Finding StandardDetails by id: {}", standarddetailsId);
        return this.wmGenericDao.findById(standarddetailsId);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public StandardDetails findById(Integer standarddetailsId) {
        LOGGER.debug("Finding StandardDetails by id: {}", standarddetailsId);
        try {
            return this.wmGenericDao.findById(standarddetailsId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No StandardDetails found with id: {}", standarddetailsId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public List<StandardDetails> findByMultipleIds(List<Integer> standarddetailsIds, boolean orderedReturn) {
        LOGGER.debug("Finding StandardDetails by ids: {}", standarddetailsIds);

        return this.wmGenericDao.findByMultipleIds(standarddetailsIds, orderedReturn);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public StandardDetails getByStandardCode(String standardCode) {
        Map<String, Object> standardCodeMap = new HashMap<>();
        standardCodeMap.put("standardCode", standardCode);

        LOGGER.debug("Finding StandardDetails by unique keys: {}", standardCodeMap);
        return this.wmGenericDao.findByUniqueKey(standardCodeMap);
    }

    @Transactional(rollbackFor = EntityNotFoundException.class, value = "School_DBTransactionManager")
    @Override
    public StandardDetails update(StandardDetails standardDetails) {
        LOGGER.debug("Updating StandardDetails with information: {}", standardDetails);

        this.wmGenericDao.update(standardDetails);
        this.wmGenericDao.refresh(standardDetails);

        return standardDetails;
    }

    @Transactional(value = "School_DBTransactionManager")
    @Override
    public StandardDetails delete(Integer standarddetailsId) {
        LOGGER.debug("Deleting StandardDetails with id: {}", standarddetailsId);
        StandardDetails deleted = this.wmGenericDao.findById(standarddetailsId);
        if (deleted == null) {
            LOGGER.debug("No StandardDetails found with id: {}", standarddetailsId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), StandardDetails.class.getSimpleName(), standarddetailsId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "School_DBTransactionManager")
    @Override
    public void delete(StandardDetails standardDetails) {
        LOGGER.debug("Deleting StandardDetails with {}", standardDetails);
        this.wmGenericDao.delete(standardDetails);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Page<StandardDetails> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all StandardDetails");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Page<StandardDetails> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all StandardDetails");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service School_DB for table StandardDetails to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service School_DB for table StandardDetails to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "School_DBTransactionManager")
    @Override
    public Page<Academics> findAssociatedAcademicses(Integer standardId, Pageable pageable) {
        LOGGER.debug("Fetching all associated academicses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("standardDetails.standardId = '" + standardId + "'");

        return academicsService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service AcademicsService instance
     */
    protected void setAcademicsService(AcademicsService service) {
        this.academicsService = service;
    }

}